# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UfeCBVD2HXEIG7W7CuPk_jnX0ZLO27fH
"""

import urllib.request
import pandas as pd
print('ok')

url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

page = urllib.request.urlopen(url)

from bs4 import BeautifulSoup

soup = BeautifulSoup(page, "lxml")

soup.title.string

print(soup.prettify())

all_tables=soup.find_all("table")
#all_tables

right_table=soup.find('table', class_='wikitable sortable')
#right_table

A=[]
B=[]
C=[]

for row in right_table.findAll('tr'):
    cells=row.findAll('td')
    if len(cells)==3:
        A.append(cells[0].find(text=True))
        B.append(cells[1].find(text=True))
        C.append(cells[2].find(text=True))

import pandas as pd
df=pd.DataFrame(A,columns=['Postal Code'])
df['Borough']=B
df['Neighborhood']=C

df.head(10)

df = df.replace(r'\n',' ', regex=True)

df.head()

df = df[df.Borough != 'Not assigned ']

df.head(10)

for index, row in df.iterrows():
  if row['Neighborhood'] == 'Not assigned ':
    row['Neighborhood'] = row['Borough']
#check if the value of column 'Neighborhood' is 'Not assgined '
#if so, replace this value by the value of the column 'Borough'

df.head()

df.reset_index(drop = True)





