# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UfeCBVD2HXEIG7W7CuPk_jnX0ZLO27fH
"""

import urllib.request
import pandas as pd
print('ok')

url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

page = urllib.request.urlopen(url)

from bs4 import BeautifulSoup

soup = BeautifulSoup(page, "lxml")

soup.title.string

print(soup.prettify())

all_tables=soup.find_all("table")
#all_tables

right_table=soup.find('table', class_='wikitable sortable')
#right_table

A=[]
B=[]
C=[]

for row in right_table.findAll('tr'):
    cells=row.findAll('td')
    if len(cells)==3:
        A.append(cells[0].find(text=True))
        B.append(cells[1].find(text=True))
        C.append(cells[2].find(text=True))

import pandas as pd
df=pd.DataFrame(A,columns=['Postal Code'])
df['Borough']=B
df['Neighborhood']=C

df.head(10)

df = df.replace(r'\n',' ', regex=True)

df.head()

df = df[df.Borough != 'Not assigned ']

df.head()

for index, row in df.iterrows():
  if row['Neighborhood'] == 'Not assigned ':
    row['Neighborhood'] = row['Borough']
#check if the value of column 'Neighborhood' is 'Not assgined '
#if so, replace this value by the value of the column 'Borough'

df.head()

df.reset_index(drop = True)

"""**QUESTION2**"""

data = pd.read_csv('http://cocl.us/Geospatial_data')
#read the csv file which contains the location of each neighborhood

data.tail()
#print the tail of the dataset to check that it had been loaded

df.head()
#check the dataframe, I notice that datas are not sorted in the same way
#Now I have to sort the values to match the location

df.sort_values(by = 'Postal Code', inplace = True)
df.reset_index(drop = True, inplace = True)
df.head()
#I sort the values of my dataframe to match the csv file

data.sort_values(by ='Postal Code', inplace = True)

data.head()
#I also sort the datas of the csv file, to ensure that they will match
#I print both datas to check that they match

df['Latitude'] = data['Latitude']
df['Longitude'] = data['Longitude']
#I add the location of the csv file to my data frame

df.head()
#Print the data frame to check that it had been added

